language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql_upgrade
  - mysql -u root -e 'CREATE DATABASE torp CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL ON torp.* TO 'admin'@'localhost';"
  - mysql -u root -e "flush privileges;"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: torp-service-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: https://github.com/KOOSANGYOON/torp #Github 주소
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  slack:
    - codesquad-members:JL8mg8juRpnTB2Fk7w8KsOES
  email:
    - nevergiveup936@naver.com
  on_success: always
  on_failure: always