language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - sudo stop mysql
  - sudo killall -9 mysqld
  - sudo mysqld_safe
  - mysql -u root
  - FLUSH PRIVILEGES;
  - UPDATE mysql.user SET Password=PASSWORD('root') WHERE User='root';
  - FLUSH PRIVILEGES;
  - exit;
  - mysql -u root -proot 'CREATE DATABASE torp;'
  - mysql -u root -proot 'CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';'
  - mysql -u root -proot 'GRANT ALL ON torp.* TO 'test'@'localhost';'

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com