language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql_upgrade
  - mysql -u root -e 'CREATE DATABASE torp;'
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL ON torp.* TO 'admin'@'localhost';"
  - mysql -u root -e "flush privileges;"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package -Dmaven.test.skip=true"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com