language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE torp'
  - mysql -u root -e "CREATE USER 'root'@'localhost'; GRANT ALL ON *.* TO 'root'@'localhost'; FLUSH PRIVILEGES;"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
#    - '$HOME/.maven'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com