language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql_upgrade
  - mysql -e 'CREATE DATABASE torp;'
  - mysql -e 'FLUSH PRIVILEGES;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
#  - mysql -u root -e "grant all privileges on *.* to 'root'@'localhost' identified by 'root' with grant option;"
  - mysql -u root -e "grant all privileges on *.* to 'root'@'localhost';"
  - mysql -e 'FLUSH PRIVILEGES;'
  - sudo service mysql restart

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com