language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE torp'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root'"
  - mysql -u root -e "GRANT ALL ON torp.* TO 'root'@'localhost'"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
#    - '$HOME/.maven'

script: "./mvnw clean package"

#before_script:
#  - mysql -u root -e 'CREATE DATABASE torp;'
#  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
#  - mysql -u root -e "GRANT ALL ON torp.* TO 'root'@'localhost';"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com