language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql_upgrade
  - mysql -u root -e 'CREATE DATABASE torp CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL ON torp.* TO 'admin'@'localhost';"
  - mysql -u root -e "flush privileges;"

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  slack:
    - codesquad-members:JL8mg8juRpnTB2Fk7w8KsOES
  email:
    - nevergiveup936@naver.com
  on_success: always
  on_failure: always