language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
#  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mysql_upgrade
  - mysql -u root -e 'CREATE DATABASE torp;'
  - mysql -u root -e "grant all privileges on *.* to 'torp'@'localhost' identified by 'root' with grant option;"
  - sudo service mysql restart
#  - mysql -e 'CREATE DATABASE torp;'
#  - sudo service mysql stop;c
#  - sudo mysql -e "use torp; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='root';FLUSH PRIVILEGES;"
#  - sudo mysql_upgrade
#  - sudo service mysql restart

#before_script:
#  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
#  - mysql -u root -e "GRANT ALL ON torp.* TO 'root'@'localhost';"
#  - mysql -u root -e 'flush privileges;'

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com