language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mysql -u root -e 'CREATE DATABASE torp;'
  - mysql -u root -e 'CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';'
  - mysql -u root -e 'GRANT ALL ON torp.* TO 'test'@'localhost';'
  - mysql -u root -e 'flush privileges;'

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nevergiveup936@naver.com